sudo: required
services:
  - docker

before_install:
  - docker build -t ttmarkka/docker-react -f Dockerfile.dev .

language: generic

- docker run -e CI=true ttmarkka/docker-react npm run test -- --coverage
script:
